# Generated by Django 5.0.6 on 2024-06-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rawdata',
            constraint=models.UniqueConstraint(fields=('invoice_number', 'customer'), name='unique_invoice_number_customer'),
        ),
    ]
